global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'flashcart-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flashcart'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):(.*)'
        replacement: 'flashcart-app'
